name: edgex-app-service-configurable
base: core18
adopt-info: app-service-config
license: Apache-2.0
summary:   The reference EdgeX App Service Configurable
title: EdgeX App Service Configurable
description: |
  The reference EdgeX app-service-configurable is built using the App
  Functions SDK. This service is provided as an easy way to get started
  with processing data flowing through EdgeX. This service leverages the
  App Functions SDK and provides a way for developers to use configuration
  instead of having to compile standalone services to utilize built in
  functions in the SDK. For a full list of supported/built-in functions
  view the documentation located here:

  https://docs.edgexfoundry.org/1.2/microservices/application/ApplServices/

  Initially the daemon in the snap is disabled - this allows the configuration
  to be modified and provided to app-service-config in
  "$SNAP_DATA/config/app-service-configurable/res" before starting.

# TODO: add armhf when the project supports this
architectures:
  - build-on: amd64
  - build-on: arm64

grade: stable
confinement: strict

# edinburgh release is epoch 1
# fuji release is epoch 2
# geneva release is epoch 3
epoch: 3

# Ideally snapcraft would generate this command-chain spec for the hooks
# automatically, but that doesn't currently work, see
# https://bugs.launchpad.net/snapd/+bug/1824255
# In the meantime, make sure that the snapcraft-runner gets generated by
# the apps by specifying the full adapter in at least one of the apps, and
# manually craft the command-chain for the configure hook here to passthrough
# to the snap.yaml
# All of this is necessary so we can use jq and other tools from inside the
# snap in the configure and install hooks
# See also https://bugs.launchpad.net/snapcraft/+bug/1848381 for specifying
# environment for hooks
passthrough:
  hooks:
    configure:
      command-chain:
        - snap/command-chain/snapcraft-runner
    install:
      command-chain:
        - snap/command-chain/snapcraft-runner

slots:
  edgex-secretstore-token:
    interface: content
    content: edgex-secretstore-token
    source:
      write: [$SNAP_DATA/edgex-application-service]

plugs:
  edgex-profiles-config:
    interface: content
    content: edgex-profiles-config
    target: $SNAP_DATA/config/res

apps:
  app-service-configurable:
    adapter: full
    command: bin/service-wrapper.sh
    command-chain:
      - bin/startup-env-var.sh
    environment:
      SecretStore_TokenFile: $SNAP_DATA/edgex-application-service/secrets-token.json
      SecretStoreExclusive_TokenFile: $SNAP_DATA/edgex-application-service/secrets-token.json
    daemon: simple
    plugs: [network, network-bind]

parts:
  go:
    plugin: nil
    source: snap/local
    build-packages: [curl]
    override-build: |
      # use dpkg architecture to figure out our target arch
      # note - we specifically don't use arch
      case "$(dpkg --print-architecture)" in
        amd64)
          FILE_NAME=go1.15.2.linux-amd64.tar.gz
          FILE_HASH=b49fda1ca29a1946d6bb2a5a6982cf07ccd2aba849289508ee0f9918f6bb4552
          ;;
        arm64)
          FILE_NAME=go1.15.2.linux-arm64.tar.gz
          FILE_HASH=c8ec460cc82d61604b048f9439c06bd591722efce5cd48f49e19b5f6226bd36d
          ;;
      esac
      # download the archive, failing on ssl cert problems
      curl https://dl.google.com/go/$FILE_NAME -O
      echo "$FILE_HASH $FILE_NAME" > sha256
      sha256sum -c sha256 | grep OK
      tar -C $SNAPCRAFT_STAGE -xf go*.tar.gz --strip-components=1
    prime:
      - "-*"

  hooks:
    source: ./hooks
    plugin: make
    after: [go]
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      make build
      install -DT ./configure "$SNAPCRAFT_PART_INSTALL/configure"
    organize:
      configure: snap/hooks/configure

  app-service-config:
    source: .
    plugin: make
    build-packages: [gcc, git, libzmq3-dev, pkg-config]
    stage-packages: [jq,libzmq5]
    after: [go]
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "1.2.0-$(date +%Y%m%d)+$(git rev-parse --short HEAD)"
    override-build: |
      cd $SNAPCRAFT_PART_SRC
      make build

      # install the service binary
      install -DT "./app-service-configurable" \
         "$SNAPCRAFT_PART_INSTALL/bin/app-service-configurable"

      # create config dirs
      find ./res -maxdepth 1 -type d -exec install -d "$SNAPCRAFT_PART_INSTALL/config/"{} \;

      # replace relative log paths in configuration.toml files with fully qualified paths
      # prefixed with $SNAP_COMMON
      find ./res -name "configuration.toml" | \
          while read fname; do
               cat "$fname" | sed -e s:\./logs/:\\'$SNAP_COMMON/'\: > \
              "$SNAPCRAFT_PART_INSTALL/config/$fname"
          done

      install -DT "./Attribution.txt" \
         "$SNAPCRAFT_PART_INSTALL/usr/share/doc/app-service-configurable/Attribution.txt"
      install -DT "./LICENSE" \
         "$SNAPCRAFT_PART_INSTALL/usr/share/doc/app-service-configurable/LICENSE"

  config-common:
    plugin: dump
    source: snap/local/runtime-helpers
